name: Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, Tag or Commit to build'
        required: false
        default: 'master'

env:
  MINGW_VERSION: "v9.0.0"
  AMDAMF_VERSION: "v1.4.23"
  NVIDIANVENC_VERSION: "n11.0.10.0"
  X264_VERSION: "0.163.3060"
  ZLIB_NG_VERSION: "2.0.3"
  AOM_VERSION: "v3.1.2.115"

jobs:
  cc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        license: [ "LGPL", "GPL" ]
        license_version: [ 2, 3 ]
        type: [ "shared" ]
        bits: [ 64 ]
        patches: [ false, true ]
    name: "Windows (${{ matrix.bits }}bit, ${{ matrix.type }}, ${{ matrix.license }}v${{ matrix.license_version}}, patched=${{ matrix.patches }})"
    env:
      BUILD_TYPE: ${{ matrix.type }}
      BUILD_BITS: ${{ matrix.bits }}
      LICENSE: ${{ matrix.license }}
      LICENSE_VERSION: ${{ matrix.license_version }}
      SCRIPTROOT: "/tmp"
    steps:
    - name: "automation: Check-out"
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1
        
    - name: "automation: Copy things to safety"
      shell: bash
      run: |
        # Copy important scripts to "safe" directory".
        cp -R -f ./patches ${SCRIPTROOT}/patches
        cp -R -f ./scripts ${SCRIPTROOT}/scripts
        chmod +x ${SCRIPTROOT}/scripts/*.sh
        cp -R -f ./addons ${SCRIPTROOT}/addons
        chmod +x ${SCRIPTROOT}/addons/*.sh

    - name: "dependency: cmake, make, pkg-config, mingw, nasm"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install \
          build-essential git \
          cmake make ninja-build \
          pkg-config \
          mingw-w64 mingw-w64-tools gcc-mingw-w64 g++-mingw-w64 \
          nasm        

    - name: "ffmpeg: Check out '${{ github.event.inputs.ref }}'"
      uses: actions/checkout@v2
      with:
        ref: "${{ github.event.inputs.ref }}"
        submodules: "recursive"
        fetch-depth: 0
        
    - name: "automation: Bootstrap"
      id: bootstrap
      shell: bash
      run: |
        . ${SCRIPTROOT}/addons/bootstrap.sh
        echo "FFmpeg v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_TWEAK}-${COMMIT}"

    - name: "automation: Apply Patches"
      if:  ${{ (matrix.patches == true) }}
      id: patch
      env:
        VERSION_MAJOR: ${{ steps.bootstrap.outputs.VERSION_MAJOR }}
        VERSION_MINOR: ${{ steps.bootstrap.outputs.VERSION_MINOR }}
        VERSION_PATCH: ${{ steps.bootstrap.outputs.VERSION_PATCH }}
        VERSION_TWEAK: ${{ steps.bootstrap.outputs.VERSION_TWEAK }}
        COMMIT: ${{ steps.bootstrap.outputs.COMMIT }}
      shell: bash
      run: |
        . ${SCRIPTROOT}/addons/patch.sh
        echo "::set-output name=name::-patched"

    - name: "automation: Run scripts"
      env:
        VERSION_MAJOR: ${{ steps.bootstrap.outputs.VERSION_MAJOR }}
        VERSION_MINOR: ${{ steps.bootstrap.outputs.VERSION_MINOR }}
        VERSION_PATCH: ${{ steps.bootstrap.outputs.VERSION_PATCH }}
        VERSION_TWEAK: ${{ steps.bootstrap.outputs.VERSION_TWEAK }}
        COMMIT: ${{ steps.bootstrap.outputs.COMMIT }}
        BUILD_ARCH: ${{ steps.bootstrap.outputs.BUILD_ARCH }}
        BUILD_TARGET: ${{ steps.bootstrap.outputs.BUILD_TARGET }}
        BUILD_PREFIX: ${{ steps.bootstrap.outputs.BUILD_PREFIX }}
        BUILD_FLAGS: ${{ steps.bootstrap.outputs.BUILD_FLAGS }}
      shell: bash
      run: |
        . ${SCRIPTROOT}/addons/run.sh

#         #if (( "${{ steps.version.outputs.major }}" >= 4 )); then
#         #  echo "::set-output name=flags::--enable-ffnvcodec --enable-nvdec --enable-cuvid --enable-nvenc"
#         #elif (( "${{ steps.version.outputs.major }}" >= 3 )); then
#         #  if (( "${{ steps.version.outputs.minor }}" >= 2 )); then
#         #    # 3.2+ has cuda, cuvid, nvenc
#         #    echo "::set-output name=flags::--enable-cuvid --enable-nvenc"
#         #  elif (( "${{ steps.version.outputs.minor }}" >= 1 )); then
#         #    # 3.1 has cuda, nvenc
#         #    echo "::set-output name=flags::--enable-nvenc"
#         #  elif (( "${{ steps.version.outputs.minor }}" >= 0 )); then
#         #    # 3.0 has nvenc
#         #    echo "::set-output name=flags::--enable-nvenc"
#         #  fi
#         #fi

# # libx264 (FFmpeg 0.5 and up, arbitrarily limited to 1.0 because I'm lazy)
#     - name: "dependency: x264 v${{ env.X264_VERSION }} (GPLv2, shared)"
#       if: ${{ (steps.version.outputs.major >= 1) && startsWith(matrix.license, 'GPL') }}
#       id: x264
#       shell: bash
#       run: |
#         curl -L -o "/tmp/x264.zip" "https://github.com/Xaymar/x264/releases/download/${X264_VERSION}/x264-${{ matrix.bits }}-shared-GPLv2.zip"
#         7z x -o/tmp/x264/ "/tmp/x264.zip"
#         sudo cp -a /tmp/x264/. /usr/${{ steps.data.outputs.cross_prefix }}/
#         cp -a /tmp/x264/bin/*.dll ./distrib/bin/
#         #echo "::set-output name=flags::--enable-libx264"

# # zlib-ng
#     - name: "dependency: zlib-ng v${{ env.ZLIB_NG_VERSION }} (Zlib license, shared)"
#       id: zlib
#       shell: bash
#       run: |
#         curl -L -o "/tmp/zlib.zip" "https://github.com/Xaymar/zlib-ng/releases/download/${ZLIB_NG_VERSION}/zlib-ng-${{ matrix.bits }}.zip"
#         7z x -o/tmp/zlib/ "/tmp/zlib.zip"
#         sudo cp -a /tmp/zlib/. /usr/${{ steps.data.outputs.cross_prefix }}/
#         cp -a /tmp/zlib/bin/*.dll ./distrib/bin/

    - name: "automation: Upload Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: "ffmpeg-${{ matrix.license }}v${{ matrix.license_version }}-${{ matrix.bits}}-${{ matrix.type }}-${{ steps.bootstrap.outputs.VERSION_MAJOR }}.${{ steps.bootstrap.outputs.VERSION_MINOR }}.${{ steps.bootstrap.outputs.VERSION_PATCH }}.${{ steps.bootstrap.outputs.VERSION_TWEAK }}-${{ steps.bootstrap.outputs.COMMIT }}${{ steps.patch.outputs.name }}"
        path: distrib
